version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: beauty_price_tracker_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: beauty123
      MYSQL_DATABASE: beauty_price_tracker
    ports:
      - "3307:3306"
    volumes:
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:


